package com.example.matharchive.config;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.example.matharchive.domain.AppUser;
import com.example.matharchive.domain.CategoryTaxonomy;
import com.example.matharchive.domain.Favorite;
import com.example.matharchive.domain.MistakeRecord;
import com.example.matharchive.domain.OperationLog;
import com.example.matharchive.domain.PracticeRecord;
import com.example.matharchive.domain.PracticeStatus;
import com.example.matharchive.domain.Question;
import com.example.matharchive.domain.ReviewStatus;
import com.example.matharchive.domain.SystemSetting;
import com.example.matharchive.repository.AppUserRepository;
import com.example.matharchive.repository.CategoryTaxonomyRepository;
import com.example.matharchive.repository.FavoriteRepository;
import com.example.matharchive.repository.MistakeRecordRepository;
import com.example.matharchive.repository.OperationLogRepository;
import com.example.matharchive.repository.PracticeRecordRepository;
import com.example.matharchive.repository.QuestionRepository;
import com.example.matharchive.repository.SystemSettingRepository;

@Configuration
public class DataSeeder {

    private static final List<String> AUTO_GENERATED_QUESTION_CODES = List.of(
            "T2024-001",
            "T2024-015",
            "T2023-005",
            "T2022-002",
            "T2021-020",
            "T2020-008",
            "T2019-011",
            "T2018-006"
    );
    private static final List<String> LEGACY_SIMULATION_PREFIXES = List.of(
            "S2021-",
            "S2022-",
            "S2023-",
            "S2024-",
            "S2025-"
    );
    private static final String LEGACY_SIMULATION_SOURCE_ORG = "系统原创仿真";
    private static final String LEGACY_SIMULATION_SUBMITTER = "系统生成";

    @Bean
    CommandLineRunner seedData(
            AppUserRepository appUserRepository,
            QuestionRepository questionRepository,
            FavoriteRepository favoriteRepository,
            MistakeRecordRepository mistakeRecordRepository,
            CategoryTaxonomyRepository categoryTaxonomyRepository,
            PracticeRecordRepository practiceRecordRepository,
            OperationLogRepository operationLogRepository,
            SystemSettingRepository systemSettingRepository
    ) {
        return args -> {
            seedUsers(appUserRepository);
            cleanupAutoGeneratedQuestions(
                    questionRepository,
                    favoriteRepository,
                    mistakeRecordRepository,
                    practiceRecordRepository
            );
            cleanupAutoGeneratedOperationLogs(operationLogRepository);
            normalizeQuestionCategories(questionRepository);
            seedCategoryTaxonomy(categoryTaxonomyRepository);
            seedSettings(systemSettingRepository);
        };
    }

    private void seedUsers(AppUserRepository appUserRepository) {
        appUserRepository.findByUsername("admin").ifPresent(user -> {
            if (!hasText(user.getPhone())) {
                user.setPhone("13800000000");
            }
            if (user.getLastLoginAt() == null) {
                user.setLastLoginAt(LocalDateTime.now().minusHours(2));
            }
            appUserRepository.save(user);
        });

        appUserRepository.findByUsername("student_01").ifPresent(user -> {
            if (!hasText(user.getPhone())) {
                user.setPhone("13900001111");
            }
            if (user.getLastLoginAt() == null) {
                user.setLastLoginAt(LocalDateTime.now().minusDays(1));
            }
            appUserRepository.save(user);
        });
    }

    private void seedQuestions(QuestionRepository questionRepository) {
        for (Question item : generatedQuestions()) {
            if (isAutoGeneratedSeedQuestion(item)) {
                continue;
            }
            if (questionRepository.existsByArchiveCode(item.getArchiveCode())) {
                continue;
            }
            questionRepository.save(item);
        }
    }

    private void cleanupAutoGeneratedQuestions(
            QuestionRepository questionRepository,
            FavoriteRepository favoriteRepository,
            MistakeRecordRepository mistakeRecordRepository,
            PracticeRecordRepository practiceRecordRepository
    ) {
        for (Question question : questionRepository.findAll()) {
            if (!isAutoGeneratedSeedQuestion(question)) {
                continue;
            }
            Long questionId = question.getId();
            favoriteRepository.deleteByQuestion_Id(questionId);
            mistakeRecordRepository.deleteByQuestion_Id(questionId);
            practiceRecordRepository.deleteByQuestion_Id(questionId);
            questionRepository.delete(question);
        }
    }

    private void cleanupAutoGeneratedOperationLogs(OperationLogRepository operationLogRepository) {
        List<OperationLog> generatedLogs = operationLogRepository.findAll().stream()
                .filter(this::isAutoGeneratedOperationLog)
                .toList();
        if (!generatedLogs.isEmpty()) {
            operationLogRepository.deleteAll(generatedLogs);
        }
    }

    private List<Question> generatedQuestions() {
        return List.of(
                question("T2024-001", 2024, "数学一", "同济大学", "高等数学", "函数与极限", "极限, 等价无穷小, 定积分", "单项选择题", "基础",
                        "设 f(x)=∫(0→x) sin(t²)/t dt，则 lim(x→0) f(x)/x = ?", "0", "1", "2", "-1",
                        "A", "利用 sin(t²)/t ~ t，可知积分主部为 x²/2，因此极限为 0。", ReviewStatus.APPROVED, "题库管理员", 10, null),
                question("T2024-015", 2024, "数学二", "哈尔滨工业大学", "线性代数", "矩阵与方程组", "矩阵, 交换子, 迹", "解答题", "强化",
                        "设矩阵 A=[1 2;3 4]，若 B 满足 AB-BA=E，分析该条件是否可成立。", null, null, null, null,
                        "不存在", "对矩阵取迹可知 tr(AB-BA)=0，而 tr(E)=2，因此条件不成立。", ReviewStatus.REJECTED, "教师上传", 8, "答案过程不完整"),
                question("T2023-005", 2023, "数学一", "西安交通大学", "概率论与数理统计", "随机变量及其分布", "正态分布, 数字特征", "填空题", "冲刺",
                        "设随机变量 X~N(0,1)，求 E(X^4)=____。", null, null, null, null,
                        "3", "标准正态分布四阶矩为 3。", ReviewStatus.APPROVED, "题库管理员", 6, null),
                question("T2022-002", 2022, "数学一", "山东大学", "高等数学", "多元函数微分学", "全微分, 偏导数, 多元函数", "单项选择题", "基础",
                        "函数 z=x²y 在点 (1,2) 处的全微分 dz = ?", "4dx+dy", "4dx+2dy", "2dx+dy", "4dx+2xdy",
                        "B", "先求偏导再代入点 (1,2)，得 dz = 4dx + 2dy。", ReviewStatus.PENDING, "学生投稿", 2, null),
                question("T2021-020", 2021, "数学一", "北京理工大学", "高等数学", "无穷级数", "狄利克雷判别法, 条件收敛", "证明题", "强化",
                        "证明级数 Σ(sin n)/n 是条件收敛。", null, null, null, null,
                        "条件收敛", "由狄利克雷判别法可证其收敛，但绝对值级数发散。", ReviewStatus.PENDING, "学生投稿", 1, null),
                question("T2020-008", 2020, "数学二", "天津大学", "线性代数", "特征值与特征向量", "特征值, 行列式, 矩阵运算", "单项选择题", "基础",
                        "设矩阵 A 的特征值为 1、1、3，则 |A^3-E| = ?", "0", "-2", "6", "12",
                        "A", "由特征值可得 A^3-E 的特征值分别为 0、0、26，因此行列式为 0。", ReviewStatus.APPROVED, "题库管理员", 16, null),
                question("T2019-011", 2019, "数学三", "中南大学", "高等数学", "定积分应用", "旋转体体积, 定积分", "解答题", "强化",
                        "利用定积分求平面图形绕 x 轴旋转所得体积。", null, null, null, null,
                        "按题设积分", "先建立积分区间，再由旋转体体积公式完成积分。", ReviewStatus.APPROVED, "题库管理员", 21, null),
                question("T2018-006", 2018, "数学三", "华中科技大学", "概率论与数理统计", "参数估计", "矩估计, 泊松分布", "单项选择题", "基础",
                        "设样本来自参数为 λ 的泊松分布，λ 的矩估计量是?", "样本均值", "样本方差", "样本中位数", "样本极差",
                        "A", "泊松分布的一阶矩等于 λ，因此矩估计量为样本均值。", ReviewStatus.APPROVED, "题库管理员", 30, null),

                question("S2025-001", 2025, "数学一", "系统原创仿真", "高等数学", "函数、极限、连续", "函数极限的计算", "单项选择题", "基础",
                        "设极限 lim(x→0) (e^x-1-x)/x² = ?", "1/2", "1", "0", "2",
                        "A", "利用 e^x=1+x+x²/2+o(x²)，分子主部为 x²/2。", ReviewStatus.APPROVED, "系统生成", 0, null),
                question("S2025-002", 2025, "数学二", "系统原创仿真", "线性代数", "矩阵", "矩阵的秩", "填空题", "基础",
                        "设 A 为 3 阶矩阵，且 r(A)=2，则其伴随矩阵 A* 的秩为 ____。", null, null, null, null,
                        "1", "对 3 阶矩阵，当 r(A)=n-1=2 时，伴随矩阵的秩为 1。", ReviewStatus.APPROVED, "系统生成", 0, null),
                question("S2025-003", 2025, "数学三", "系统原创仿真", "概率论与数理统计", "随机变量的数字特征", "数学期望与方差", "单项选择题", "基础",
                        "设随机变量 X 服从参数为 p 的 0-1 分布，则 D(X) = ?", "p", "p(1-p)", "1-p", "p²",
                        "B", "0-1 分布的方差公式为 D(X)=p(1-p)。", ReviewStatus.APPROVED, "系统生成", 0, null),
                question("S2025-004", 2025, "数学一", "系统原创仿真", "高等数学", "一元函数积分学", "变限积分", "解答题", "强化",
                        "设 F(x)=∫(0→x²)(1+t³)dt，求 F'(x)。", null, null, null, null,
                        "2x(1+x^6)", "由变上限积分求导公式，F'(x)=(1+(x²)³)·(x²)'=2x(1+x^6)。", ReviewStatus.APPROVED, "系统生成", 0, null),
                question("S2025-005", 2025, "数学二", "系统原创仿真", "线性代数", "矩阵的特征值与特征向量", "特征值与特征向量", "填空题", "强化",
                        "设二阶矩阵 A 的一个特征值为 2，且 tr(A)=5，则另一特征值为 ____。", null, null, null, null,
                        "3", "矩阵全部特征值之和等于迹，因此另一特征值为 5-2=3。", ReviewStatus.APPROVED, "系统生成", 0, null),

                question("S2024-101", 2024, "数学一", "系统原创仿真", "高等数学", "一元函数微分学", "函数的单调性、极值与最值", "单项选择题", "基础",
                        "函数 f(x)=x-lnx (x>0) 的最小值为 ?", "0", "1", "2", "e",
                        "B", "f'(x)=1-1/x，驻点 x=1，且 f''(x)=1/x²>0，故最小值为 f(1)=1。", ReviewStatus.APPROVED, "系统生成", 5, null),
                question("S2024-102", 2024, "数学二", "系统原创仿真", "线性代数", "行列式", "行列式", "单项选择题", "基础",
                        "计算行列式|1 1 1; 1 2 3; 1 4 9| = ?", "1", "2", "3", "4",
                        "B", "按第一行展开或利用初等变换可得行列式值为 2。", ReviewStatus.APPROVED, "系统生成", 5, null),
                question("S2024-103", 2024, "数学三", "系统原创仿真", "概率论与数理统计", "多维随机变量及其分布", "边缘分布和条件分布", "填空题", "强化",
                        "设二维随机变量 (X,Y) 的密度为 f(x,y)=2 (0<y<x<1)，其边缘密度 f_X(x)=____。", null, null, null, null,
                        "2x", "对 y 在 (0,x) 上积分，得 f_X(x)=∫(0→x)2dy=2x。", ReviewStatus.APPROVED, "系统生成", 5, null),
                question("S2024-104", 2024, "数学一", "系统原创仿真", "高等数学", "常微分方程", "可分离变量的微分方程与齐次方程", "解答题", "基础",
                        "求微分方程 y'=y/x 满足 y(1)=2 的解。", null, null, null, null,
                        "y=2x", "分离变量得 dy/y=dx/x，积分得 ln|y|=ln|x|+C，由初值条件得 y=2x。", ReviewStatus.APPROVED, "系统生成", 5, null),
                question("S2024-105", 2024, "数学三", "系统原创仿真", "概率论与数理统计", "参数估计与假设检验", "矩估计和最大似然估计", "单项选择题", "强化",
                        "设样本来自参数为 λ 的泊松分布，则 λ 的极大似然估计为 ?", "样本均值", "样本方差", "样本极差", "样本中位数",
                        "A", "写出似然函数并取对数求导，可得极大似然估计为样本均值。", ReviewStatus.APPROVED, "系统生成", 5, null),

                question("S2023-101", 2023, "数学一", "系统原创仿真", "高等数学", "多元函数微分学", "方向导数和梯度", "单项选择题", "强化",
                        "设 z=x²+y²，则 z 在点 (1,-1) 沿方向 l=(3,4) 的方向导数为 ?", "2/5", "-2/5", "1", "-1",
                        "B", "梯度为 (2x,2y)，在 (1,-1) 处为 (2,-2)，与单位方向向量 (3/5,4/5) 点乘得 -2/5。", ReviewStatus.APPROVED, "系统生成", 10, null),
                question("S2023-102", 2023, "数学二", "系统原创仿真", "线性代数", "线性方程组", "线性方程组", "填空题", "基础",
                        "齐次线性方程组 Ax=0 有 3 个未知量，若 r(A)=2，则其解空间维数为 ____。", null, null, null, null,
                        "1", "解空间维数等于未知量个数减去秩，即 3-2=1。", ReviewStatus.APPROVED, "系统生成", 10, null),
                question("S2023-103", 2023, "数学三", "系统原创仿真", "概率论与数理统计", "随机事件和概率", "随机事件和概率", "单项选择题", "基础",
                        "设 A,B 相互独立，P(A)=1/2，P(B)=1/3，则 P(A∪B) = ?", "1/6", "2/3", "5/6", "1/3",
                        "B", "P(A∪B)=P(A)+P(B)-P(AB)=1/2+1/3-1/6=2/3。", ReviewStatus.APPROVED, "系统生成", 10, null),
                question("S2023-104", 2023, "数学一", "系统原创仿真", "高等数学", "无穷级数", "常数项级数敛散性的判定", "单项选择题", "基础",
                        "级数 Σ(1/n²) 的敛散性是 ?", "发散", "条件收敛", "绝对收敛", "无法确定",
                        "C", "这是 p 级数，p=2>1，因此绝对收敛。", ReviewStatus.APPROVED, "系统生成", 10, null),
                question("S2023-105", 2023, "数学一", "系统原创仿真", "高等数学", "一元函数积分学", "不定积分的计算", "填空题", "基础",
                        "∫xe^x dx = ____ + C。", null, null, null, null,
                        "(x-1)e^x", "分部积分，取 u=x，dv=e^x dx，可得结果为 (x-1)e^x+C。", ReviewStatus.APPROVED, "系统生成", 10, null),

                question("S2022-101", 2022, "数学一", "系统原创仿真", "高等数学", "多元函数积分学", "重积分的计算", "解答题", "强化",
                        "计算二重积分 ∫∫D (x+y)dσ，其中 D=[0,1]×[0,2]。", null, null, null, null,
                        "3", "∫(0→1)∫(0→2)(x+y)dydx = ∫(0→1)(2x+2)dx = 3。", ReviewStatus.APPROVED, "系统生成", 15, null),
                question("S2022-102", 2022, "数学二", "系统原创仿真", "线性代数", "向量", "向量内积与向量正交", "单项选择题", "基础",
                        "向量 a=(1,2,-1), b=(2,-1,0) 的关系是 ?", "平行", "正交", "线性无关但不正交", "无法判断",
                        "B", "a·b=1×2+2×(-1)+(-1)×0=0，因此二者正交。", ReviewStatus.APPROVED, "系统生成", 15, null),
                question("S2022-103", 2022, "数学三", "系统原创仿真", "概率论与数理统计", "大数定律和中心极限定理", "大数定律和中心极限定理", "单项选择题", "冲刺",
                        "设 X1,…,Xn 独立同分布，E(Xi)=μ，D(Xi)=σ²>0，则当 n→∞ 时，(X̄-μ)/(σ/√n) 的极限分布为 ?", "N(0,1)", "Poisson(1)", "U(0,1)", "χ²(1)",
                        "A", "由中心极限定理，标准化后的样本均值依分布收敛于标准正态分布。", ReviewStatus.APPROVED, "系统生成", 15, null),
                question("S2022-104", 2022, "数学一", "系统原创仿真", "高等数学", "一元函数微分学", "泰勒公式", "填空题", "基础",
                        "当 x→0 时，e^x = 1+x+____+o(x²)。", null, null, null, null,
                        "x²/2", "在 0 点展开的泰勒公式为 e^x=1+x+x²/2+o(x²)。", ReviewStatus.APPROVED, "系统生成", 15, null),
                question("S2022-105", 2022, "数学三", "系统原创仿真", "概率论与数理统计", "数理统计的基本概念", "数理统计的基本概念", "单项选择题", "基础",
                        "下列量中，属于统计量的是 ?", "总体均值 μ", "总体方差 σ²", "样本均值 X̄", "参数 p",
                        "C", "统计量是仅由样本决定而不含未知参数的函数，样本均值满足定义。", ReviewStatus.APPROVED, "系统生成", 15, null),

                question("S2021-101", 2021, "数学一", "系统原创仿真", "高等数学", "函数、极限、连续", "无穷小量的比较", "单项选择题", "基础",
                        "极限 lim(x→0) (1-cos x)/x² = ?", "0", "1/2", "1", "2",
                        "B", "由 cos x=1-x²/2+o(x²)，分子主部为 x²/2。", ReviewStatus.APPROVED, "系统生成", 20, null),
                question("S2021-102", 2021, "数学二", "系统原创仿真", "线性代数", "二次型", "二次型", "单项选择题", "强化",
                        "二次型 x1²+2x1x2+x2² 对应的矩阵为 ?", "[1 0;0 1]", "[1 1;1 1]", "[2 1;1 2]", "[1 -1;-1 1]",
                        "B", "二次型可写为 x^T A x，其中 A 的非对角元取交叉项系数的一半，故 A=[[1,1],[1,1]]。", ReviewStatus.APPROVED, "系统生成", 20, null),
                question("S2021-103", 2021, "数学三", "系统原创仿真", "概率论与数理统计", "随机变量及其分布", "随机变量及其分布", "填空题", "基础",
                        "若随机变量 X 服从参数为 λ 的指数分布，则 E(X)=____。", null, null, null, null,
                        "1/λ", "指数分布的数学期望公式为 E(X)=1/λ。", ReviewStatus.APPROVED, "系统生成", 20, null),
                question("S2021-104", 2021, "数学一", "系统原创仿真", "高等数学", "常微分方程", "常系数齐次线性微分方程", "解答题", "强化",
                        "求微分方程 y''-3y'+2y=0 的通解。", null, null, null, null,
                        "y=C1e^x+C2e^(2x)", "特征方程 r²-3r+2=0，根为 1 和 2，因此通解为 y=C1e^x+C2e^(2x)。", ReviewStatus.APPROVED, "系统生成", 20, null),
                question("S2021-105", 2021, "数学二", "系统原创仿真", "线性代数", "矩阵的特征值与特征向量", "矩阵的相似与相似对角化", "证明题", "冲刺",
                        "证明：若 n 阶矩阵 A 有 n 个互不相同的特征值，则 A 可对角化。", null, null, null, null,
                        "可对角化", "不同特征值对应的特征向量线性无关，因此可取 n 个线性无关的特征向量构成基，A 与对角矩阵相似。", ReviewStatus.APPROVED, "系统生成", 20, null)
        );
    }

    private void seedCategoryTaxonomy(CategoryTaxonomyRepository categoryTaxonomyRepository) {
        for (CategoryOutline outline : categoryOutlines()) {
            if (!categoryTaxonomyRepository.existsBySubjectAndChapterNameAndKnowledgeTagIsNull(outline.subject(), outline.chapterName())) {
                categoryTaxonomyRepository.save(taxonomy(
                        outline.subject(),
                        outline.subjectOrder(),
                        outline.chapterName(),
                        outline.chapterOrder(),
                        null,
                        null
                ));
            }
            for (int i = 0; i < outline.knowledgeTags().size(); i++) {
                String knowledgeTag = outline.knowledgeTags().get(i);
                if (categoryTaxonomyRepository.existsBySubjectAndChapterNameAndKnowledgeTag(
                        outline.subject(),
                        outline.chapterName(),
                        knowledgeTag
                )) {
                    continue;
                }
                categoryTaxonomyRepository.save(taxonomy(
                        outline.subject(),
                        outline.subjectOrder(),
                        outline.chapterName(),
                        outline.chapterOrder(),
                        knowledgeTag,
                        i + 1
                ));
            }
        }
    }

    private void normalizeQuestionCategories(QuestionRepository questionRepository) {
        List<Question> questions = questionRepository.findAll();
        boolean changed = false;
        for (Question question : questions) {
            changed |= remapQuestion(question);
        }
        if (changed) {
            questionRepository.saveAll(questions);
        }
    }

    private void seedFavoritesAndMistakes(
            AppUserRepository appUserRepository,
            QuestionRepository questionRepository,
            FavoriteRepository favoriteRepository,
            MistakeRecordRepository mistakeRecordRepository
    ) {
        if (favoriteRepository.count() > 0 || mistakeRecordRepository.count() > 0) {
            return;
        }

        appUserRepository.findByUsername("student_01").ifPresent(student -> {
            List<Question> questions = questionRepository.findAll();
            if (questions.size() < 4) {
                return;
            }

            Favorite favoriteOne = new Favorite();
            favoriteOne.setUser(student);
            favoriteOne.setQuestion(questions.get(0));

            Favorite favoriteTwo = new Favorite();
            favoriteTwo.setUser(student);
            favoriteTwo.setQuestion(questions.get(2));

            MistakeRecord mistakeOne = new MistakeRecord();
            mistakeOne.setUser(student);
            mistakeOne.setQuestion(questions.get(1));
            mistakeOne.setNote("矩阵交换子与迹的性质需要再复习。");

            MistakeRecord mistakeTwo = new MistakeRecord();
            mistakeTwo.setUser(student);
            mistakeTwo.setQuestion(questions.get(3));
            mistakeTwo.setNote("全微分计算时容易漏掉系数。");

            favoriteRepository.saveAll(List.of(favoriteOne, favoriteTwo));
            mistakeRecordRepository.saveAll(List.of(mistakeOne, mistakeTwo));
        });
    }

    private void seedPracticeRecords(
            AppUserRepository appUserRepository,
            QuestionRepository questionRepository,
            PracticeRecordRepository practiceRecordRepository
    ) {
        if (practiceRecordRepository.count() > 0) {
            return;
        }

        appUserRepository.findByUsername("student_01").ifPresent(student -> {
            List<Question> questions = questionRepository.findAll();
            if (questions.size() < 4) {
                return;
            }

            practiceRecordRepository.saveAll(List.of(
                    practice(student, questions.get(0), PracticeStatus.VIEWED, 6),
                    practice(student, questions.get(0), PracticeStatus.MASTERED, 6),
                    practice(student, questions.get(1), PracticeStatus.VIEWED, 5),
                    practice(student, questions.get(1), PracticeStatus.MISTAKE, 5),
                    practice(student, questions.get(2), PracticeStatus.REVIEW, 3),
                    practice(student, questions.get(2), PracticeStatus.MASTERED, 2),
                    practice(student, questions.get(3), PracticeStatus.MISTAKE, 1),
                    practice(student, questions.get(3), PracticeStatus.REVIEW, 0)
            ));
        });
    }

    private void seedSettings(SystemSettingRepository systemSettingRepository) {
        if (systemSettingRepository.count() > 0) {
            return;
        }

        systemSettingRepository.saveAll(List.of(
                setting("site_name", "考研数学真题分类管理系统"),
                setting("admin_email", "admin@example.com"),
                setting("contact_phone", "13800001234"),
                setting("site_intro", "系统提供真题管理、题目审核、学习分析和用户服务等功能。"),
                setting("record_number", "陕ICP备12345678号-1"),
                setting("version", "v1.0.0"),
                setting("publish_date", "2026-04-01"),
                setting("team_name", "考研数学项目组")
        ));
    }

    private void seedOperationLogs(OperationLogRepository operationLogRepository) {
        if (operationLogRepository.count() > 0) {
            return;
        }

        operationLogRepository.saveAll(List.of(
                log("登录系统", "用户管理", "管理员登录后台", "成功", 3),
                log("审核通过", "题目审核", "通过题目 T2024-001", "成功", 2),
                log("审核驳回", "题目审核", "驳回题目 T2024-015", "成功", 1),
                log("更新设置", "系统设置", "修改站点基础信息", "成功", 0)
        ));
    }

    private Question question(
            String archiveCode,
            int year,
            String paperName,
            String sourceOrg,
            String subject,
            String chapterName,
            String knowledgeTags,
            String questionType,
            String difficulty,
            String stemText,
            String optionA,
            String optionB,
            String optionC,
            String optionD,
            String answer,
            String analysis,
            ReviewStatus reviewStatus,
            String submitterName,
            int daysAgo,
            String rejectReason
    ) {
        Question question = new Question();
        question.setArchiveCode(archiveCode);
        question.setYearValue(year);
        question.setPaperName(paperName);
        question.setSourceOrg(sourceOrg);
        question.setSubject(subject);
        question.setChapterName(chapterName);
        question.setKnowledgeTags(knowledgeTags);
        question.setQuestionType(questionType);
        question.setDifficultyLevel(difficulty);
        question.setStemText(stemText);
        question.setOptionA(optionA);
        question.setOptionB(optionB);
        question.setOptionC(optionC);
        question.setOptionD(optionD);
        question.setAnswerText(answer);
        question.setAnalysisText(analysis);
        question.setReviewStatus(reviewStatus);
        question.setSubmitterName(submitterName);
        question.setRejectReason(rejectReason);
        question.setCreatedDate(LocalDate.of(Math.min(year + 1, 2026), 4, 14));
        question.setSubmittedAt(LocalDateTime.now().minusDays(daysAgo));
        question.setUpdatedAt(LocalDateTime.now().minusDays(Math.max(daysAgo - 1, 0)));
        return question;
    }

    private CategoryTaxonomy taxonomy(
            String subject,
            int subjectOrder,
            String chapterName,
            int chapterOrder,
            String knowledgeTag,
            Integer knowledgeOrder
    ) {
        CategoryTaxonomy taxonomy = new CategoryTaxonomy();
        taxonomy.setSubject(subject);
        taxonomy.setSubjectOrder(subjectOrder);
        taxonomy.setChapterName(chapterName);
        taxonomy.setChapterOrder(chapterOrder);
        taxonomy.setKnowledgeTag(knowledgeTag);
        taxonomy.setKnowledgeOrder(knowledgeOrder);
        return taxonomy;
    }

    private PracticeRecord practice(AppUser user, Question question, PracticeStatus status, int daysAgo) {
        PracticeRecord record = new PracticeRecord();
        record.setUser(user);
        record.setQuestion(question);
        record.setStatus(status);
        record.setSourcePage("SEED");
        record.setPracticedAt(LocalDateTime.now().minusDays(daysAgo));
        return record;
    }

    private SystemSetting setting(String key, String value) {
        SystemSetting setting = new SystemSetting();
        setting.setSettingKey(key);
        setting.setSettingValue(value);
        setting.setUpdatedAt(LocalDateTime.now());
        return setting;
    }

    private OperationLog log(String type, String module, String detail, String status, int hoursAgo) {
        OperationLog log = new OperationLog();
        log.setOperatorName("admin");
        log.setOperatorRole("管理员");
        log.setActionType(type);
        log.setActionModule(module);
        log.setActionDetail(detail);
        log.setActionStatus(status);
        log.setIpAddress("127.0.0.1");
        log.setOperatedAt(LocalDateTime.now().minusHours(hoursAgo));
        return log;
    }

    private boolean remapQuestion(Question question) {
        boolean changed = false;

        if ("高等数学".equals(question.getSubject()) && "函数与极限".equals(question.getChapterName())) {
            question.setChapterName("函数、极限、连续");
            question.setKnowledgeTags("函数极限的计算, 无穷小量的比较");
            changed = true;
        }
        if ("高等数学".equals(question.getSubject()) && "定积分应用".equals(question.getChapterName())) {
            question.setChapterName("一元函数积分学");
            question.setKnowledgeTags("定积分的应用, 定积分的计算");
            changed = true;
        }
        if ("线性代数".equals(question.getSubject()) && "矩阵与方程组".equals(question.getChapterName())) {
            question.setChapterName("矩阵");
            question.setKnowledgeTags("矩阵的运算与变换, 伴随矩阵与可逆矩阵");
            changed = true;
        }
        if ("线性代数".equals(question.getSubject()) && "特征值与特征向量".equals(question.getChapterName())) {
            question.setChapterName("矩阵的特征值与特征向量");
            question.setKnowledgeTags("特征值与特征向量");
            changed = true;
        }
        if ("概率论与数理统计".equals(question.getSubject()) && "参数估计".equals(question.getChapterName())) {
            question.setChapterName("参数估计与假设检验");
            question.setKnowledgeTags("矩估计和最大似然估计, 估计量的无偏性");
            changed = true;
        }

        return changed;
    }

    private List<CategoryOutline> categoryOutlines() {
        return List.of(
                outline("高等数学", 1, "函数、极限、连续", 1, List.of("数列敛散性的判定", "函数极限的计算", "确定极限中的参数", "无穷小量的比较", "函数的连续性")),
                outline("高等数学", 1, "一元函数微分学", 2, List.of("导数与微分的概念", "导数与微分的计算", "导数的几何意义", "函数的单调性、极值与最值", "曲线的凹凸性、拐点及渐近线", "方程根的存在性与个数", "不等式的证明", "微分中值定理", "泰勒公式")),
                outline("高等数学", 1, "一元函数积分学", 3, List.of("不定积分的计算", "定积分的概念、性质及几何意义", "定积分的计算", "变限积分", "反常积分的计算与敛散性", "定积分的应用")),
                outline("高等数学", 1, "多元函数微分学", 4, List.of("偏导数的概念与计算", "全微分的概念与计算", "多元函数微分学的几何应用", "方向导数和梯度", "多元函数的极值问题")),
                outline("高等数学", 1, "多元函数积分学", 5, List.of("重积分的概念与性质", "交换积分次序与坐标系之间的转换", "重积分的计算", "重积分的应用", "第一类曲线积分", "第二类曲线积分", "第一类曲面积分", "第二类曲面积分", "旋度的定义")),
                outline("高等数学", 1, "无穷级数", 6, List.of("常数项级数敛散性的判定", "幂级数的收敛半径、收敛区间和收敛域", "幂级数的和函数及幂级数展开式", "傅里叶级数")),
                outline("高等数学", 1, "常微分方程", 7, List.of("线性微分方程的解的结构", "可分离变量的微分方程与齐次方程", "一阶非齐次线性微分方程", "常系数齐次线性微分方程", "常系数非齐次线性微分方程", "其他方程", "微分方程的应用")),
                outline("线性代数", 2, "行列式", 1, List.of()),
                outline("线性代数", 2, "矩阵", 2, List.of("矩阵的运算与变换", "伴随矩阵与可逆矩阵", "矩阵的秩")),
                outline("线性代数", 2, "向量", 3, List.of("向量组的线性相关性", "向量组之间的线性表示", "向量内积与向量正交")),
                outline("线性代数", 2, "线性方程组", 4, List.of()),
                outline("线性代数", 2, "矩阵的特征值与特征向量", 5, List.of("特征值与特征向量", "矩阵的相似与相似对角化")),
                outline("线性代数", 2, "二次型", 6, List.of()),
                outline("概率论与数理统计", 3, "随机事件和概率", 1, List.of()),
                outline("概率论与数理统计", 3, "随机变量及其分布", 2, List.of()),
                outline("概率论与数理统计", 3, "多维随机变量及其分布", 3, List.of("二维随机变量及其分布", "边缘分布和条件分布")),
                outline("概率论与数理统计", 3, "随机变量的数字特征", 4, List.of("数学期望与方差", "协方差与相关系数")),
                outline("概率论与数理统计", 3, "大数定律和中心极限定理", 5, List.of()),
                outline("概率论与数理统计", 3, "数理统计的基本概念", 6, List.of()),
                outline("概率论与数理统计", 3, "参数估计与假设检验", 7, List.of("估计量的无偏性", "矩估计和最大似然估计", "区间估计和置信区间", "假设检验"))
        );
    }

    private CategoryOutline outline(String subject, int subjectOrder, String chapterName, int chapterOrder, List<String> knowledgeTags) {
        return new CategoryOutline(subject, subjectOrder, chapterName, chapterOrder, knowledgeTags);
    }

    private boolean hasText(String value) {
        return value != null && !value.isBlank();
    }

    private boolean isAutoGeneratedSeedQuestion(Question question) {
        return question != null && isAutoGeneratedSeedQuestion(question.getArchiveCode());
    }

    private boolean isAutoGeneratedSeedQuestion(String archiveCode) {
        return AUTO_GENERATED_QUESTION_CODES.contains(archiveCode) || isLegacySimulationQuestion(archiveCode);
    }

    private boolean isLegacySimulationQuestion(String archiveCode) {
        if (!hasText(archiveCode)) {
            return false;
        }
        return LEGACY_SIMULATION_PREFIXES.stream().anyMatch(archiveCode::startsWith);
    }

    private boolean isAutoGeneratedOperationLog(OperationLog log) {
        if (log == null) {
            return false;
        }
        String detail = log.getActionDetail();
        if (!hasText(detail)) {
            return false;
        }
        if ("初始化数据".equals(log.getActionType())) {
            return true;
        }
        if ("创建系统默认配置".equals(detail)) {
            return true;
        }
        for (String archiveCode : AUTO_GENERATED_QUESTION_CODES) {
            if (detail.contains(archiveCode)) {
                return true;
            }
        }
        for (String prefix : LEGACY_SIMULATION_PREFIXES) {
            if (detail.contains(prefix)) {
                return true;
            }
        }
        return false;
    }

    private record CategoryOutline(
            String subject,
            int subjectOrder,
            String chapterName,
            int chapterOrder,
            List<String> knowledgeTags
    ) {
    }
}
